// HTTP reference data: common status codes and request/response headers.
// Descriptions are kept deliberately short — this is a lookup table, not docs.

export const STATUS_CODES = [
  ["100", "Continue", "继续"],
  ["101", "Switching Protocols", "切换协议（如升级到 WebSocket）"],
  ["102", "Processing", "处理中（WebDAV）"],
  ["103", "Early Hints", "预加载提示"],
  ["200", "OK", "请求成功"],
  ["201", "Created", "已创建"],
  ["202", "Accepted", "已接受（异步处理中）"],
  ["203", "Non-Authoritative Information", "非权威信息"],
  ["204", "No Content", "无内容"],
  ["205", "Reset Content", "重置内容"],
  ["206", "Partial Content", "部分内容（断点续传）"],
  ["207", "Multi-Status", "多状态（WebDAV）"],
  ["208", "Already Reported", "已报告（WebDAV）"],
  ["226", "IM Used", "实例操作已应用"],
  ["300", "Multiple Choices", "多种选择"],
  ["301", "Moved Permanently", "永久重定向"],
  ["302", "Found", "临时重定向"],
  ["303", "See Other", "查看其他（POST 后转 GET）"],
  ["304", "Not Modified", "未修改（缓存有效）"],
  ["307", "Temporary Redirect", "临时重定向（保持方法）"],
  ["308", "Permanent Redirect", "永久重定向（保持方法）"],
  ["400", "Bad Request", "请求错误"],
  ["401", "Unauthorized", "未认证"],
  ["402", "Payment Required", "需要付费"],
  ["403", "Forbidden", "禁止访问"],
  ["404", "Not Found", "未找到"],
  ["405", "Method Not Allowed", "方法不允许"],
  ["406", "Not Acceptable", "不可接受"],
  ["407", "Proxy Authentication Required", "需要代理认证"],
  ["408", "Request Timeout", "请求超时"],
  ["409", "Conflict", "冲突"],
  ["410", "Gone", "已删除"],
  ["411", "Length Required", "需要 Content-Length"],
  ["412", "Precondition Failed", "前置条件失败"],
  ["413", "Content Too Large", "请求体过大"],
  ["414", "URI Too Long", "URI 过长"],
  ["415", "Unsupported Media Type", "不支持的媒体类型"],
  ["416", "Range Not Satisfiable", "范围不满足"],
  ["417", "Expectation Failed", "Expect 失败"],
  ["418", "I'm a Teapot", "我是茶壶（彩蛋）"],
  ["421", "Misdirected Request", "请求导向错误"],
  ["422", "Unprocessable Content", "无法处理的内容"],
  ["423", "Locked", "已锁定（WebDAV）"],
  ["424", "Failed Dependency", "依赖失败（WebDAV）"],
  ["425", "Too Early", "过早请求"],
  ["426", "Upgrade Required", "需要升级协议"],
  ["428", "Precondition Required", "需要前置条件"],
  ["429", "Too Many Requests", "请求过多（限流）"],
  ["431", "Request Header Fields Too Large", "请求头过大"],
  ["451", "Unavailable For Legal Reasons", "因法律原因不可用"],
  ["500", "Internal Server Error", "服务器内部错误"],
  ["501", "Not Implemented", "未实现"],
  ["502", "Bad Gateway", "网关错误"],
  ["503", "Service Unavailable", "服务不可用"],
  ["504", "Gateway Timeout", "网关超时"],
  ["505", "HTTP Version Not Supported", "HTTP 版本不支持"],
  ["506", "Variant Also Negotiates", "变体协商错误"],
  ["507", "Insufficient Storage", "存储不足（WebDAV）"],
  ["508", "Loop Detected", "检测到循环（WebDAV）"],
  ["510", "Not Extended", "未扩展"],
  ["511", "Network Authentication Required", "需要网络认证"],
];

export const HTTP_HEADERS = [
  ["Accept", "Client-declared response media types it can handle", "客户端声明可接受的响应类型"],
  ["Accept-Encoding", "Compression algorithms the client supports (gzip, br…)", "客户端支持的压缩算法（gzip、br…）"],
  ["Accept-Language", "Preferred natural languages", "期望的自然语言"],
  ["Authorization", "Credentials: Bearer token, Basic auth…", "认证凭据：Bearer、Basic 等"],
  ["Cache-Control", "Caching directives (no-cache, max-age…)", "缓存指令（no-cache、max-age…）"],
  ["Connection", "Keep-alive / close control for the connection", "连接控制（keep-alive / close）"],
  ["Content-Disposition", "inline / attachment; filename for downloads", "inline/attachment；下载文件名"],
  ["Content-Encoding", "Compression applied to the body (gzip, br)", "正文压缩方式（gzip、br）"],
  ["Content-Length", "Body size in bytes", "正文字节数"],
  ["Content-Type", "Body media type (application/json…)", "正文媒体类型（application/json…）"],
  ["Cookie", "Stored cookies sent to the server", "发送给服务器的 Cookie"],
  ["ETag", "Entity version tag for conditional requests", "实体版本标记，用于条件请求"],
  ["Host", "Target host and port (required in HTTP/1.1)", "目标主机与端口（HTTP/1.1 必需）"],
  ["If-Modified-Since", "Conditional fetch: only if changed after date", "条件请求：此后有修改才返回"],
  ["If-None-Match", "Conditional fetch: only if ETag differs", "条件请求：ETag 不匹配才返回"],
  ["Last-Modified", "Last modification time of the resource", "资源最后修改时间"],
  ["Location", "Redirect target URL (3xx responses)", "重定向目标地址（3xx）"],
  ["Origin", "Request origin (CORS / CSRF checks)", "请求来源（CORS / CSRF 校验）"],
  ["Referer", "Previous page URL that led to this request", "来源页面地址"],
  ["Retry-After", "How long to wait before retrying (429/503)", "重试等待时间（429/503）"],
  ["Server", "Server software banner", "服务器软件标识"],
  ["Set-Cookie", "Cookie set by the server", "服务器下发的 Cookie"],
  ["User-Agent", "Client product identifier", "客户端标识"],
  ["WWW-Authenticate", "Auth challenge for 401 responses", "401 的认证挑战信息"],
  ["X-Forwarded-For", "Original client IP chain (proxies)", "原始客户端 IP 链（代理）"],
  ["X-Forwarded-Proto", "Original scheme (http/https) behind a proxy", "代理前的原始协议（http/https）"],
  ["X-Requested-With", "Marks AJAX requests (XMLHttpRequest)", "标记 AJAX 请求（XMLHttpRequest）"],
  ["Access-Control-Allow-Origin", "Allowed origins for CORS", "CORS 允许的来源"],
  ["Access-Control-Allow-Methods", "Allowed methods for CORS preflight", "CORS 预检允许的方法"],
  ["Access-Control-Allow-Headers", "Allowed headers for CORS preflight", "CORS 预检允许的请求头"],
  ["Access-Control-Max-Age", "How long preflight results can be cached", "预检结果可缓存时长"],
  ["Strict-Transport-Security", "HSTS: force HTTPS for a period", "HSTS：强制使用 HTTPS"],
  ["Content-Security-Policy", "CSP: restrict loaded resources/scripts", "CSP：限制资源/脚本来源"],
  ["X-Content-Type-Options", "nosniff: forbid MIME-type sniffing", "nosniff：禁止 MIME 嗅探"],
  ["X-Frame-Options", "Frame embedding control (clickjacking)", "iframe 嵌入控制（防点击劫持）"],
];
